"""PaperSpine V5 figure-integration boundary."""

from .body_integration import build_figure_body_contract, validate_figure_body_contract
from .academic_stage_orchestrator import (
    ACTIVE_STAGES,
    AcademicStageContractError,
    AcademicStageOrchestrator,
    validate_academic_stage_answer,
    validate_academic_stage_result,
)
from .canonical_artifacts import (
    compile_canonical_artifacts,
    finalize_surface_receipt,
    materialize_canonical_artifacts,
    prepare_surface_receipt,
    record_canonical_artifacts,
    validate_surface_receipt,
)
from .contracts import ContractError, load_integration_job, validate_figure_requests, validate_review_decision
from .coordinator import IntegrationCoordinator
from .figure_correction import (
    build_pdf_text_overlay,
    FigureCorrectionError,
    FigureCorrectionService,
    review_target_size_legibility,
    pdf_render_region_sha256,
    validate_target_size_legibility_receipt,
    validate_figure_correction_receipt,
)
from .product_kernel import (
    IdempotencyConflictError,
    ProductKernel,
    RepositoryCompatibilityError,
    RevisionConflictError,
    StateRepository,
    TaskNotFoundError,
    TaskRegistry,
    WriterLeaseError,
)
from .product_runner import ProductRunner, ProductRunnerCompatibilityError
from .product_runner_contracts import (
    RUNNER_PROTOCOL_VERSION,
    RUNNER_VERSION,
    validate_material_source_ledger,
    validate_run_configuration,
    validate_run_contract,
    validate_runner_issue,
    validate_runner_state,
)
from .publication_pipeline import PublicationPipelineService
from .maturity_acceptance import (
    EVALUATOR_IDENTITY,
    MaturityAcceptanceError,
    build_fixture_freeze_receipt,
    build_independent_evaluation_receipt,
    evaluate_preregistered_runs,
    validate_preregistered_protocol,
    validate_protocol_design,
    verify_fixture_freeze_receipt,
    verify_independent_evaluation_receipt,
)
from .maturity_acceptance_v2 import (
    MaturityAcceptanceV2Error,
    authoritative_context_from_evidence,
    build_fixture_freeze_receipt_v2,
    build_independent_evaluation_receipt_v2,
    current_evaluator_hashes_v2,
    derive_hard_checks_v2,
    evaluate_target_adaptation_v2,
    load_protocol_target_profile,
    protocol_sha256_v2,
    validate_independent_evaluator_receipt_v2,
    validate_preregistered_protocol_v2,
    validate_protocol_design_v2,
    verify_fixture_freeze_receipt_v2,
    verify_independent_evaluation_receipt_v2,
)
from .panel_selection import PanelSelectionError, select_panel_aware_candidate
from .quality_readiness import (
    CheckResult,
    QualityContractError,
    QualitySubject,
    ReadinessCompiler,
    ReadinessTier,
    TruthStatus,
    build_obligation_manifest,
    dependency_closure,
    predicate_receipt,
    validate_claim_inventory,
    validate_evidence_registry,
    validate_review_receipt,
    validate_readiness_verdict_payload,
    validate_target_research,
)
from .research_argument_service import ResearchArgumentStageService

__all__ = [
    "ContractError",
    "ACTIVE_STAGES",
    "AcademicStageContractError",
    "AcademicStageOrchestrator",
    "IntegrationCoordinator",
    "FigureCorrectionError",
    "FigureCorrectionService",
    "build_pdf_text_overlay",
    "ProductKernel",
    "RepositoryCompatibilityError",
    "TaskRegistry",
    "StateRepository",
    "TaskNotFoundError",
    "RevisionConflictError",
    "WriterLeaseError",
    "IdempotencyConflictError",
    "ProductRunner",
    "ProductRunnerCompatibilityError",
    "PublicationPipelineService",
    "EVALUATOR_IDENTITY",
    "MaturityAcceptanceError",
    "build_fixture_freeze_receipt",
    "build_independent_evaluation_receipt",
    "evaluate_preregistered_runs",
    "validate_preregistered_protocol",
    "validate_protocol_design",
    "verify_fixture_freeze_receipt",
    "verify_independent_evaluation_receipt",
    "MaturityAcceptanceV2Error",
    "authoritative_context_from_evidence",
    "build_fixture_freeze_receipt_v2",
    "build_independent_evaluation_receipt_v2",
    "current_evaluator_hashes_v2",
    "derive_hard_checks_v2",
    "evaluate_target_adaptation_v2",
    "load_protocol_target_profile",
    "protocol_sha256_v2",
    "validate_independent_evaluator_receipt_v2",
    "validate_preregistered_protocol_v2",
    "validate_protocol_design_v2",
    "verify_fixture_freeze_receipt_v2",
    "verify_independent_evaluation_receipt_v2",
    "PanelSelectionError",
    "ResearchArgumentStageService",
    "RUNNER_VERSION",
    "RUNNER_PROTOCOL_VERSION",
    "CheckResult",
    "QualityContractError",
    "QualitySubject",
    "ReadinessCompiler",
    "ReadinessTier",
    "TruthStatus",
    "build_obligation_manifest",
    "build_figure_body_contract",
    "compile_canonical_artifacts",
    "finalize_surface_receipt",
    "load_integration_job",
    "materialize_canonical_artifacts",
    "prepare_surface_receipt",
    "record_canonical_artifacts",
    "validate_surface_receipt",
    "select_panel_aware_candidate",
    "validate_figure_body_contract",
    "validate_figure_requests",
    "validate_review_decision",
    "dependency_closure",
    "predicate_receipt",
    "validate_claim_inventory",
    "validate_evidence_registry",
    "validate_review_receipt",
    "validate_readiness_verdict_payload",
    "validate_target_research",
    "validate_material_source_ledger",
    "validate_run_configuration",
    "validate_run_contract",
    "validate_runner_issue",
    "validate_runner_state",
    "validate_academic_stage_answer",
    "validate_academic_stage_result",
    "review_target_size_legibility",
    "pdf_render_region_sha256",
    "validate_figure_correction_receipt",
    "validate_target_size_legibility_receipt",
]
